### ISSUE TITLE
NEED HELP

### ISSUE THREAD

**Issue by strunz983** [nwestfall/netsparkerscanrunner#2]
Hi My OS is 
Linux kali 5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-2kali1 (2019-08-22) x86_64 GNU/Linux 
and when i want to install netsparkerscanrunner i get this
npm install -g netsparker-scan-runner
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! code E404
npm ERR! 404 Not Found: netsparker-scan-runner@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-03T13_33_04_932Z-debug.log

so i do that 
npm install runner.js
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
+ runner.js@1.0.1
added 80 packages from 99 contributors in 5.807s

but when i want to star netsparker-scan-runner --help i got this 
netsparker-scan-runner --help
bash: netsparker-scan-runner: command not found

npm --version 5.8.0

Thank you :)

**Comment by nwestfall** [comment]
@strunz983 did you end up solving this?  Sorry for just seeing it.
